import os
import json
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Any

class MeetingMinutesAutomation:
    """
    会議の文字起こしデータやテキストログを解析し、
    決定事項やアクションアイテムを抽出して構造化された議事録を自動生成するツール。
    """
    def __init__(self, input_dir: str, output_dir: str):
        self.input_dir = Path(input_dir)
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def process_meetings(self) -> None:
        if not self.input_dir.exists():
            print(f"入力ディレクトリが存在しません: {self.input_dir}")
            return

        for file_path in self.input_dir.glob("*.json"):
            try:
                data = self._load_json(file_path)
                summary = self._extract_key_points(data.get("transcript", ""))
                self._export_markdown(
                    title=data.get("title", "Untitled Meeting"),
                    summary=summary,
                    date=data.get("date", str(datetime.now().date()))
                )
            except Exception as e:
                print(f"エラー発生 ({file_path.name}): {e}")

    def _load_json(self, file_path: Path) -> Dict[str, Any]:
        with open(file_path, "r", encoding="utf-8") as f:
            return json.load(f)

    def _extract_key_points(self, transcript: str) -> Dict[str, List[str]]:
        lines = transcript.splitlines()
        decisions = [line.strip() for line in lines if "決定" in line or "Approved" in line]
        action_items = [line.strip() for line in lines if "タスク" in line or "TODO" in line]
        
        return {
            "decisions": decisions if decisions else ["特筆すべき決定事項なし"],
            "action_items": action_items if action_items else ["特筆すべきアクションアイテムなし"]
        }

    def _export_markdown(self, title: str, summary: Dict[str, List[str]], date: str) -> None:
        safe_title = "".join(c for c in title if c.isalnum() or c in (' ', '_', '-')).rstrip()
        filename = f"{date}_{safe_title.replace(' ', '_')}.md"
        out_path = self.output_dir / filename

        content = f"# 議事録: {title}\n**実施日:** {date}\n\n## 1. 決定事項\n"
        content += '\n'.join([f'- {d}' for d in summary['decisions']])
        content += "\n\n## 2. アクションアイテム (TODO)\n"
        content += '\n'.join([f'- {a}' for a in summary['action_items']])
        content += "\n\n---\n*Generated by MeetingMinutesAutomation Tool.*\n"
        
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"議事録を出力しました: {out_path}")

if __name__ == "__main__":
    base_path = Path(__file__).parent
    input_path = base_path / "inputs"
    output_path = base_path / "outputs"
    
    automation = MeetingMinutesAutomation(str(input_path), str(output_path))
    automation.process_meetings()